name: Update README with Recent Changes

on:
  push:
    branches:
      - main  # Change if using a different default branch

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate file change log
        run: |
          echo "## Recent Updates" > recent_changes.md
          echo "$(date)" >> recent_changes.md
          echo "" >> recent_changes.md
          git log -n 5 --pretty=format:"- %h %s (%an, %ar)" >> recent_changes.md
          echo "" >> recent_changes.md
          cat recent_changes.md >> README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Updated README with recent changes" || echo "No changes to commit"
          git push
